// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlogzhvfcahjhufwthlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsb2d6aHZmY2Foamh1Znd0aGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODE2NTYsImV4cCI6MjA2NzY1NzY1Nn0.VEMMs5ZLDb6XT7c44pHr8WY2H_LaBEY44FraYGOBIaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});